[package]
name = "iron_golf"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
tokio = { version = "1.48.0", features = ["full"] }
